export const END_POINT_API = {
  PRODUCTS: "/api/Products",
  QUOTATION: "/api/Quotation",
  LOGIN: "/api/User/login",
  REGISTER: "/api/User/register",
  ALL_QUOTATION: "/api/Quotation/GetAllSubmitedQuotations",
  ARTICLES: "/api/Articles",
  PROJECT: "/api/Project",
  PRODUCTS_STYLE: "/api/Products/GetListStyle",
  PRODUCTS_HOME_STYLE: "/api/Products/GetListHomeStyle",
  PRODUCTS_CONSTRUCTOR_STYLE: "/api/Products/GetListConstructionStyles",
  GET_CURRENT_QUOTATION: "/api/Quotation/GetSubmitedQuotationsOfUser",
  SUBMIT_QUOTATION: "/api/Quotation/SubmitQuotation",
  ADMIN_DASHBOARD: "/admin/dashboard",
  USER: "/api/AccountManager",
  CATEGORY: "/api/Category",
};
